### ISSUE TITLE
Should free_environ() be used in ft_x functions? 

### ISSUE THREAD

**Issue by hosuzuki** [tsudo42/minishell#11]
Memory leaks of environ were gone after placing free_environ() in builtin_exit and main.c before exit and return. 
Should free_environ() be placed in ft_x functions for same reason?

**Comment by tsudo42** [comment]
Still Reachableなleakは特段の理由がない限り許容できると考えています。
Definitely Lostは避ける必要があると考えているのですが、これが発生しますか?
