### ISSUE TITLE
シンボリックリンクの実行権限がなくてもファイルを実行できるはずが、できない

### ISSUE THREAD

**Issue by hosuzuki** [tsudo42/minishell#12]
bashのあるべき挙動
```
# ファイル作成
bash-3.2$ echo "echo hello" > exe && chmod +x exe
bash-3.2$ ln -s exe symexe
# シンボリックリンクの実行権限を削除
bash-3.2$ chmod -h -x symexe
# 権限確認
bash-3.2$ ls -l
total 8
-rwxr-xr-x  1 nafuka  staff  11  3  3 21:14 exe
lrw-r--r--  1 nafuka  staff   3  3  3 21:14 symexe -> exe
# コマンド実行確認
bash-3.2$ ./symexe 
hello
```

minishellでは、ワカモレで確認したが、
最後のコマンドを実行すると`hello`ではなく、
`minishell: Exec format error`が表示される

**Comment by tsudo42** [comment]
`Exec format error` は execve で発生するエラー（errno 8）。
exeにはshebangあるいは拡張子がないため、これが発生する。
bashは、execをbashのスクリプトと見做しているようだ。

https://stackoverflow.com/questions/12296308/shell-script-working-fine-without-shebang-line-why

**Comment by tsudo42** [comment]
**execveに失敗した時のエラーメッセージには、execpathが含まれる。**
