### ISSUE TITLE
export：環境変数の設定（引数が特殊なケース）

### ISSUE THREAD

**Issue by hosuzuki** [tsudo42/minishell#23]
以下、２つの違いに対して、対応不要としているが、いちおう確認。
・引数に=がない場合
・引数に+=がふくまれている場合（オプションとみなす）

bashのあるべき挙動
```
bash-3.2$ export TEST
bash-3.2$ env | grep TEST
bash-3.2$ export | grep TEST
declare -x TEST
bash-3.2$ export HOGE=
bash-3.2$ env | grep HOGE
HOGE=
bash-3.2$ export | grep HOGE
declare -x HOGE=""
bash-3.2$ export TEST=42
bash-3.2$ export TEST+=tokyo
bash-3.2$ env | grep TEST
TEST=42tokyo
bash-3.2$ 
```

minishellの挙動
```
minishell> export TEST
export: 'TEST': not a valid identifier　←ここが違う
minishell> env | grep TEST
minishell> export | grep TEST
minishell> export HOGE=
minishell> env | grep HOGE
HOGE=
minishell> export | grep HOGE
declare -x HOGE=""
minishell> export TEST=42
minishell> export TEST+=tokyo
export: 'TEST+=tokyo': not a valid identifier　←ここが違う
minishell> env | grep TEST
TEST=42
minishell> 
```

**Comment by tsudo42** [comment]
exportは、`=`と`+=`だけなのかを確認する必要がある。

**Comment by hosuzuki** [comment]
> exportは、`=`と`+=`だけなのかを確認する必要がある。

bashとbashrefのPFDでも確認しましたが、発見できず。

下記のサイトにて、（3.1.10 Appending and Prepending (Override Style Syntax)[]）
上書き機能をもつシンタックス （“:=”, “.=”, “=.”, “+=”, and “=+”）をすべてためしたましたが、
exportで使えるものは`+=`だけでした。
https://docs.yoctoproject.org/bitbake/bitbake-user-manual/bitbake-user-manual-metadata.html#conditional-syntax-overrides
