### ISSUE TITLE
グローバル変数について素朴な疑問：extern char **environ 

### ISSUE THREAD

**Issue by hosuzuki** [tsudo42/minishell#24]
extern char **environ を現在environ.hに記載してあるが、グローバル変数としてみなされないか?

**Comment by tsudo42** [comment]
environは外部で定義されたグローバル変数なので、別に扱うの流行があるようです。

https://discord.com/channels/691903146909237289/758513091096477746/996003408517529610

**Comment by tsudo42** [comment]
ただし、LINES COLUMNSのこともあるので、今のenvironを流用するやり方とは別の、environ以外の変数で環境変数を保持する方法も考えます。
