### ISSUE TITLE
SHLVL：minishell起動中、./minishellを実行した場合のSHLVLのアップデート

### ISSUE THREAD

**Issue by hosuzuki** [tsudo42/minishell#35]
minishellの中で、./minishellを実行した場合、環境変数のSHLVLがアップデートされていない。
exitを実行したときも同様。

**Comment by tsudo42** [comment]
https://github.com/bminor/bash/blob/9439ce094c9aa7557a9d53ac7b412a23aa66e36b/variables.c#L816-L860

**Comment by tsudo42** [comment]
bash起動時にセットされる変数
```
$ env -i bash
bash-3.2$ export
declare -x OLDPWD
declare -x PWD="/Users/tsudo/codespace/tsudo42/minishell"
declare -x SHLVL="1"
```

**Comment by tsudo42** [comment]
cd実行時（成功時？）に
- `PWD`はexportされずに更新される
- `OLDPWD`は元の`PWD`の値で更新される
  - `PWD`がNULLの場合、空文字で更新される

**Comment by tsudo42** [comment]
`$_`はminishell起動時に除いて良さそう
